"""add subnet to settings

Revision ID: 3a38404c0bb9
Revises: af3fb381c4a1
Create Date: 2025-09-15 21:39:07.149238

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a38404c0bb9'
down_revision = 'af3fb381c4a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('subnet', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'subnet')
    # ### end Alembic commands ###
