"""Add progress and IP tracking to ScanTask

Revision ID: 6a9e96e0507d
Revises: 704a38340575
Create Date: 2025-09-12 12:02:38.652069

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a9e96e0507d'
down_revision = '704a38340575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_tasks', sa.Column('current_ip', sa.String(), nullable=True))
    op.add_column('scan_tasks', sa.Column('total_ips', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_tasks', 'total_ips')
    op.drop_column('scan_tasks', 'current_ip')
    # ### end Alembic commands ###
