"""Initial clean migration

Revision ID: a8d500e677e5
Revises: 
Create Date: 2025-09-11 16:58:57.022827

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8d500e677e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_groups_id'), table_name='asset_groups')
    op.drop_index(op.f('ix_asset_groups_name'), table_name='asset_groups')
    op.execute("DROP TABLE asset_groups CASCADE")
    op.drop_index(op.f('ix_operations_id'), table_name='operations')
    op.drop_index(op.f('ix_operations_name'), table_name='operations')
    op.execute("DROP TABLE operations CASCADE")
    op.execute("DROP TABLE asset_group_association CASCADE")
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.execute("DROP TABLE jobs CASCADE")
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_name'), table_name='assets')
    op.execute("DROP TABLE assets CASCADE")
    op.drop_index(op.f('ix_ip_addresses_id'), table_name='ip_addresses')
    op.drop_index(op.f('ix_ip_addresses_ip'), table_name='ip_addresses')
    op.execute("DROP TABLE ip_addresses CASCADE")
    op.execute("DROP TABLE asset_group_label_association CASCADE")
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_ip'), table_name='devices')
    op.execute("DROP TABLE devices CASCADE")
    op.execute("DROP TABLE asset_label_association CASCADE")
    op.drop_index(op.f('ix_scan_tasks_id'), table_name='scan_tasks')
    op.execute("DROP TABLE scan_tasks CASCADE")
    op.drop_index(op.f('ix_scans_id'), table_name='scans')
    op.execute("DROP TABLE scans CASCADE")
    op.drop_index(op.f('ix_labels_id'), table_name='labels')
    op.drop_index(op.f('ix_labels_name'), table_name='labels')
    op.execute("DROP TABLE labels CASCADE")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labels',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('labels_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='labels_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_labels_name'), 'labels', ['name'], unique=True)
    op.create_index(op.f('ix_labels_id'), 'labels', ['id'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('scan_task_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('scan_data', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('scans_device_id_fkey')),
    sa.ForeignKeyConstraint(['scan_task_id'], ['scan_tasks.id'], name=op.f('scans_scan_task_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('scans_pkey'))
    )
    op.create_index(op.f('ix_scans_id'), 'scans', ['id'], unique=False)
    op.create_table('scan_tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('target', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('scan_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('scan_tasks_pkey'))
    )
    op.create_index(op.f('ix_scan_tasks_id'), 'scan_tasks', ['id'], unique=False)
    op.create_table('asset_label_association',
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('label_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('asset_label_association_asset_id_fkey')),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], name=op.f('asset_label_association_label_id_fkey'))
    )
    op.create_table('devices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mac', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vendor', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_seen', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('hostname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('os_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('os_family', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('os_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('scan_data', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('devices_pkey'))
    )
    op.create_index(op.f('ix_devices_ip'), 'devices', ['ip'], unique=True)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_table('asset_group_label_association',
    sa.Column('asset_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('label_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_group_id'], ['asset_groups.id'], name=op.f('asset_group_label_association_asset_group_id_fkey')),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], name=op.f('asset_group_label_association_label_id_fkey'))
    )
    op.create_table('ip_addresses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('ip_addresses_asset_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ip_addresses_pkey'))
    )
    op.create_index(op.f('ix_ip_addresses_ip'), 'ip_addresses', ['ip'], unique=False)
    op.create_index(op.f('ix_ip_addresses_id'), 'ip_addresses', ['id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('assets_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mac', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('scan_data', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('custom_fields', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='assets_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_assets_name'), 'assets', ['name'], unique=False)
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('operation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('asset_ids', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('asset_group_ids', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('results', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('params', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], name=op.f('jobs_operation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('jobs_pkey'))
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_table('asset_group_association',
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('asset_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_group_id'], ['asset_groups.id'], name=op.f('asset_group_association_asset_group_id_fkey')),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('asset_group_association_asset_id_fkey'))
    )
    op.create_table('operations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('api_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('api_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('api_headers', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('api_body', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('operations_pkey'))
    )
    op.create_index(op.f('ix_operations_name'), 'operations', ['name'], unique=False)
    op.create_index(op.f('ix_operations_id'), 'operations', ['id'], unique=False)
    op.create_table('asset_groups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('asset_groups_pkey'))
    )
    op.create_index(op.f('ix_asset_groups_name'), 'asset_groups', ['name'], unique=False)
    op.create_index(op.f('ix_asset_groups_id'), 'asset_groups', ['id'], unique=False)
    # ### end Alembic commands ###
