"""Add discovered_devices to scan_tasks

Revision ID: g2b3c4d5e6f7
Revises: f1a2b3c4d5e6
Create Date: 2025-01-27 12:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'g2b3c4d5e6f7'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add discovered_devices column to scan_tasks table
    op.add_column('scan_tasks', sa.Column('discovered_devices', sa.Integer(), nullable=True, default=0))
    
    # Update existing scan tasks to have discovered_devices = 0
    op.execute("UPDATE scan_tasks SET discovered_devices = 0 WHERE discovered_devices IS NULL")
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop discovered_devices column from scan_tasks table
    op.drop_column('scan_tasks', 'discovered_devices')
    
    # ### end Alembic commands ###
